export const DEFAULT_EDGE_RULER_VISION_PROMPT = [
  'You are testing whether a vision model can understand an edge-axis coordinate ruler over an image.',
  '',
  'The image contains a rectangular coordinate grid:',
  '- Column numbers are printed along the top edge.',
  '- Row numbers are printed along the left edge.',
  '- Interior cells do not necessarily repeat their coordinate labels.',
  '- A cell coordinate is written as [column,row], for example [6,4].',
  '',
  'Task:',
  '1. Read the edge ruler and infer the coordinate cell layout.',
  '2. Describe what visible image content appears in different important cells.',
  '3. Choose at least 12 meaningful cells distributed across the whole image, including corners, center, and visually distinctive areas.',
  '4. If a cell is empty or unclear, say so explicitly.',
  '5. Do not invent objects that are not visible.',
  '',
  'Return strict JSON only, no markdown, no explanation outside JSON.',
  'Schema:',
  '{',
  '  "understandsEdgeRuler": true,',
  '  "grid": { "columns": 16, "rows": 9 },',
  '  "confidence": 0.0,',
  '  "observations": [',
  '    {',
  '      "coordinate": [1, 1],',
  '      "content": "visible content in this cell",',
  '      "confidence": 0.0',
  '    }',
  '  ],',
  '  "axisReadingNotes": "short note about how you used the top and left axis labels",',
  '  "failureModes": ["only include issues if any"]',
  '}',
].join('\n')
